name: daily-run

on: 
    push:

env:
    SECRET: ${{ secrets.SECRET }}

jobs:
    Daily-Run:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4
            - name: Install Dependencies
              run: pip install -r requirements.txt 
            - name: create tmp dir
              run: mkdir -p .secret
            - name: create tmp file
              run: echo $SECRET > .secret/cred.json
            - name: run app
              run: python main.py
