name: daily-run

on: 
    schedule:
      - cron: "25 13 * * *"

env:
    SECRET: ${{ secrets.SECRET }}

jobs:
    Daily-Run:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4
            - name: Install Dependencies
              run: pip install -r requirements.txt 
            - name: create tmp dir
              run: mkdir -p secrets
            - name: create tmp file
              run: echo $SECRET > secrets/cred.json
            - name: run app
              run: python main.py
            - name: ls
              run: ls -la
            - name: rm
              run: rm -rf secrets
